### ISSUE TITLE
About sqlcipher

### ISSUE THREAD

**Issue by xingyun86** [sqlcipher/sqlcipher-android-tests#18]
Why don't have mips mips x64? Could you help me?

**Comment by sjlombardo** [comment]
@xingyun86 x86_64 libraries were added in the last release of SQLCipher. However, MIPS devices are not particularly common, and we have received very little interest in supporting that architecture so far. Do you have an urgent requirement for MIPS, or are you just inquiring in general?

**Comment by xingyun86** [comment]
No such requirement。But I think it should have。Thanks for your reply。
