### ISSUE TITLE
不兼容android 7.0

### ISSUE THREAD

**Issue by xulingchung2016** [sqlcipher/sqlcipher-android-tests#20]
在android 7.0系统下不能运行

**Comment by sjlombardo** [comment]
你使用什么版本的SQLCipher？

**Comment by xulingchung2016** [comment]
3.4.0

**Comment by sjlombardo** [comment]
@xulingchung2016 Support for Android N was added in SQLCipher 3.5.x. If you upgrade to 3.5.7 it will likely resolve the problem you are seeing.

**Comment by xulingchung2016** [comment]
ok ,Thank you ,I will try it.
