### ISSUE TITLE
Add Licensing Information

### ISSUE THREAD

**Issue by commonsguy** [sqlcipher/sqlcipher-android-tests#23]
Neither the repo nor the source code seem to have any license information. Technically speaking, as a result, nobody is allowed to use anything in the repo, since we don't have any rights to use it.

**Comment by developernotes** [comment]
Hi @commonsguy 

This is a good point, we will adjust this soon. Thanks!

**Comment by developernotes** [comment]
Hi @commonsguy 

Just wanted to provide an update, the test suite now includes a proper [license](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/LICENSE). Thanks!
