### ISSUE TITLE
[rawExecSQL] How to handle try catch exception when use rawExecSQL ?

### ISSUE THREAD

**Issue by chihung93** [sqlcipher/sqlcipher-android-tests#25]
I'm using this code base on your Unit Test 👍 
https://github.com/sqlcipher/sqlcipher-android-tests/blob/86318cc315836edf5a064de0e35dc5de21e149b2/app/src/main/java/net/zetetic/tests/ClosedDatabaseTest.java

But it doesn't work.

```
try {
                // should throw IllegalStateException:
                database.rawExecSQL("SELECT 1;");

                // should not get here:
                Log.e(ZeteticApplication.TAG, "SQLiteDatabase.rawExecSQL() did NOT throw exception on closed database");
                return false;
            } catch (IllegalStateException e) {
                Log.v(ZeteticApplication.TAG, "SQLiteDatabase.rawExecSQL() did throw exception on closed database OK", e);
            }
```

**Comment by developernotes** [comment]
Hi @chihung93 

Are you using the latest master of the test suite? I ask because you referenced a specific git blob. Does it crash on a specific emulator/device? If so, what is the Android API version and device you are running where you experience the crash? Thanks!

**Comment by chihung93** [comment]
It crashed because the sql script was wrong, but I wanted  to avoid crashing when running any sql script .
It happens on every device.

My device : 
zenfone - android 6.0
Jacs - android  5.0

Sql cipher - Version : 3.5.8

**Comment by developernotes** [comment]
Hi @chihung93 

That specific test is running through various scenarios where it should throw an exception because the [database is closed](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/ClosedDatabaseTest.java#L36-L38). Can you try updating to 3.5.9 and try running the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on your devices and let us know what you are seeing.

**Comment by chihung93** [comment]
So sorry, this is my fault. I forget to close the database using an IllegalStateException, I have to replace it with SQLiteException and it has worked.
Thanks.

**Comment by developernotes** [comment]
Hello @chihung93 

We are happy everything is working properly for you now. Take care!
