### ISSUE TITLE
rawExecSQL too slow ?

### ISSUE THREAD

**Issue by chihung93** [sqlcipher/sqlcipher-android-tests#26]
Hello, guys
Why is the rawExecSQL command slower than execSQL?
rawExecSQL too slow.

thanks.

**Comment by developernotes** [comment]
Hi @chihung93 

I have just replied to your question that was cross posted to our discuss site [here](https://discuss.zetetic.net/t/why-is-the-rawexecsql-command-slower-than-execsql/2645). I am going to close this, however feel free to reply on our discuss site. Thanks!
