### ISSUE TITLE
why have to choose the name "zetetic" ?  

### ISSUE THREAD

**Issue by laurentquark** [sqlcipher/sqlcipher-android-tests#28]
thx

**Comment by developernotes** [comment]
Hi @laurentquark 

What are you referring to exactly with regard to choosing the name zetetic?

**Comment by laurentquark** [comment]
hi, https://rationalwiki.org/wiki/Zetetic

**Comment by developernotes** [comment]
Hi @laurentquark 

[Zetetic](https://www.zetetic.net/) is the name of the company behind [SQLCipher](https://www.zetetic.net/sqlcipher/). I am going to close this Github issue as it is not related to the SQLCipher for Android test suite.
