### ISSUE TITLE
Unsupported Gradle JVM

### ISSUE THREAD

**Issue by madmiraal** [sqlcipher/sqlcipher-android-tests#46]
Gradle build fails with the message:
```
Unsupported Gradle JVM.

Your build is currently configured to use Java 17.0.10 and Gradle 6.8.3.

Possible solutions:
 - Upgrade to Gradle 8.5 and re-sync
 - Upgrade to Gradle 7.2 and re-sync
```
Gradle 6.8.3 only supports JVMs up to 15.[[1](https://docs.gradle.org/current/userguide/compatibility.html)] and the newest JVM that is still supported is JVM11![[2](https://en.wikipedia.org/wiki/Java_version_history)]

JVM(LTS) 17[[2](https://en.wikipedia.org/wiki/Java_version_history)] and Gradle 7.2[[3](https://gradle.org/releases/)] were released in 2021, and the current version of Gradle (8.10) supports JVM 23[[4](https://docs.gradle.org/8.10/release-notes.html)].

1. https://docs.gradle.org/current/userguide/compatibility.html
2. https://en.wikipedia.org/wiki/Java_version_history
3. https://gradle.org/releases/
4. https://docs.gradle.org/8.10/release-notes.html

**Comment by developernotes** [comment]
Hi @madmiraal,

This project is a test suite which supported `android-database-sqlcipher`, a deprecated library. That said, I have updated the Gradle reference, you should be able to pull from master and build within Android Studio.

**Comment by madmiraal** [comment]
Will there be a test suite for the new [SQLCipher for Android](https://zetetic.net/sqlcipher/sqlcipher-for-android/) library?

**Comment by developernotes** [comment]
Hi @madmiraal,

Yes, there is an [existing test suite](https://github.com/sqlcipher/sqlcipher-android/tree/master/sqlcipher/src/androidTest) within the `sqlcipher-android` project itself.
