### ISSUE TITLE
Repetitive testing option

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/sqlcipher-android-tests#8]
I was able to automatically repeat the testing through ~~10~~ _9_ rounds with the following changes which are very primitive:

``` diff
--- a/src/main/java/net/zetetic/tests/TestSuiteRunner.java
+++ b/src/main/java/net/zetetic/tests/TestSuiteRunner.java
@@ -42,9 +42,20 @@ public class TestSuiteRunner extends AsyncTask<ResultNotifier, TestResult, Void>
         }
     }

-    private List<SQLCipherTest> getTestsToRun(){
+    private List<SQLCipherTest> getTestsToRun() {
         List<SQLCipherTest> tests = new ArrayList<SQLCipherTest>();

+        //addTests(tests);
+
+        for (int i=1; i<10; ++i) {
+            tests.add(new RoundMarkerTest(i));
+            addTests(tests);
+        }
+
+        return tests;
+    }
+
+    private void addTests(List<SQLCipherTest> tests) {
         tests.add(new AttachDatabaseTest());
         tests.add(new CipherMigrateTest());
         tests.add(new GetTypeFromCrossProcessCursorWrapperTest());
@@ -86,7 +97,23 @@ public class TestSuiteRunner extends AsyncTask<ResultNotifier, TestResult, Void>
         tests.add(new RawRekeyTest());
         tests.add(new ClosedDatabaseTest());
         tests.add(new CorruptDatabaseTest());
+    }

-        return tests;
+    class RoundMarkerTest extends SQLCipherTest {
+        final int testRound;
+
+        RoundMarkerTest(int test_round) {
+            testRound = test_round;
+        }
+
+        @Override
+        public boolean execute(SQLiteDatabase database) {
+            return true;
+        }
+
+        @Override
+        public String getName() {
+            return "Test round " + testRound;
+        }
     }
 }
```

Unfortunately, if the screen locks, the testing app will crash when I unlock the screen.

Also, the Cipher Migrate test only passes the first time.

Better to have an extra button to repeat the test suite (or a part of it) for a period of several hours. Even better would be to run multiple tests in parallel threads and see how it holds up.

**Comment by developernotes** [comment]
@brodybits interesting, I wonder if the failure is just due to improper clean up of database files.  We should probably expunge the working directory of database files at the end of each test if we are not already, I would need to verify.

**Comment by UnkownMr** [comment]
Hi：
I had a problem when I use sqlcipher to encrypt the database:
1.Declare the Camera permissions in AndroidManifest.xml.
2.Using Config.ARGB_8888 configuration, the JPG picture into Bitmap.
Meet the above conditions，app will flash back.

This problem is only on the use of the MTK chip on the phone.
Could you please help me to see this question.
Thank you very much

Here is code:
package com.ricky.android.sqlitecipher;

import java.util.List;

import com.lidroid.xutils.BitmapUtils;
import com.ricky.android.sqlitecipher.dao.StudentDAO;
import com.ricky.android.sqlitecipher.dao.StudentDAOImpl;
import com.ricky.android.sqlitecipher.model.Student;
import com.ricky.android.sqlitecipher.util.Logger;

import android.app.Activity;
import android.graphics.Bitmap.Config;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.ImageView;

public class MainActivity extends Activity implements OnClickListener {

	private static final String TAG = MainActivity.class.getSimpleName();
	
	private Button bt_insert;
	private Button bt_query;
	private StudentDAO studentDAO;
	private ImageView image;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		
		findViewById();
		setListener();
		processLogic();
		
		BitmapUtils bitmapUtils = new BitmapUtils(this);
		bitmapUtils.configDefaultBitmapConfig(Config.ARGB_8888);
		bitmapUtils.display(image, "https://www.baidu.com/img/bd_logo1.png");
	}

	private void findViewById() {
		
		bt_insert = (Button) findViewById(R.id.bt_insert);
		bt_query = (Button) findViewById(R.id.bt_query);
		image = (ImageView) findViewById(R.id.img);
	}

	private void setListener() {
		bt_insert.setOnClickListener(this);
		bt_query.setOnClickListener(this);
	}

	private void processLogic() {
		
		studentDAO = new StudentDAOImpl(this);
		
	}

	@Override
	public void onClick(View v) {
		switch (v.getId()) {
		case R.id.bt_insert:
			
			Student stu = new Student();
			stu.setName("Mike");
			stu.setAge(24);
			
			long id = studentDAO.insert(stu);
			
			Logger.i(TAG, "insert id="+id);
			
			break;

		case R.id.bt_query:
			
			List<Student> list = studentDAO.query();
			if(list!=null){
				Logger.i(TAG, "student list size="+list.size());
			}else{
				Logger.i(TAG, "student list is empty");
			}
			
			break;
			
		default:
			break;
		}
	}
}

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.ricky.android.sqlitecipher"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="9"
        android:targetSdkVersion="17" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA"/>
    

    <application
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**Comment by brodybits** [comment]
I think it would be nice if we can add some more stability testing:)
